name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment_production:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes (force-sync)
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            cd /home/opc/bizzyBot
            # stáhni reference a ukliď staré
            git fetch origin --prune
            # srovnej lokální main přesně na origin/main (obejde staré nastavení na logs-repair)
            git checkout -B main origin/main

      - name: Restart BizzyBot service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            echo "=============== Restart BizzyBot Service ==============="
            cd /home/opc/bizzyBot
            # žádný další git pull – už jsme srovnali výše
            docker compose down && docker compose up -d --build
