name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment_production:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            cd /home/opc/bizzyBot
            git pull

      - name: Restart BizzyBot service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            echo "================== Restart BizzyBot Service =================="
            sudo systemctl daemon-reload
            sudo systemctl restart bizzybot.service
            sudo systemctl status bizzybot.service --no-pager
            echo "Deployment dokončen."

