name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment_production:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment on SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            echo "================== Pull Changes =================="
            cd /home/opc/bizzyBot
            git pull

            echo "================== Stop Bot =================="
              pkill -f "python3 bot.py" || echo "Bot už neběžel."

            echo "================== Start Bot =================="
            nohup python3 bot.py > bot.log 2>&1 &

            echo "Deployment dokončen. "

